/**
 * The client's reference art, taken apart into pieces.
 *
 * Portada-Background.png used to be pasted into the hero whole, which made the
 * cover a screenshot of the reference: a fixed 941x1672 crop, dead space at every
 * other viewport, and nothing reusable further down the page. These are the same
 * marks as independent elements — each carries its own viewBox, takes its colour
 * from props, and can be placed and sized wherever it earns its place.
 *
 * Outlines come from src/art/traced-marks.ts (generated by
 * scripts/trace-reference-art.mjs). The flat geometry — arch, wedge, disc — is
 * authored here, because it is plain geometry and recomposing beats tracing.
 */
import { useId } from 'react';
import type { CSSProperties } from 'react';
import {
  AMPERSAND_PATH,
  AMPERSAND_VIEWBOX,
  GLASS_PATH,
  GLASS_VIEWBOX,
  POD_OUTLINE,
  POD_RIBS,
  POD_VIEWBOX,
} from './traced-marks';

/** Client palette, from Paleta-de-Colores.png. */
export const INK = '#0d0e0b';
export const CREAM = '#f6eee4';
export const WINE = '#5e2023';
export const EUCALYPTUS = '#475548';
export const FOREST = '#272c24';

interface MarkProps {
  className?: string;
  /** Fill colour. Defaults to the reference's black. */
  tone?: string;
  style?: CSSProperties;
}

/**
 * Wine glass silhouette.
 *
 * `splitAt` reproduces the one move that gives the reference its character: the
 * glass changes colour partway across, so it reads solid against the cream and
 * inverted against the green. Pass the fraction of the glass's width where the
 * ground behind it changes, plus the colour it should become there.
 */
export function WineGlassMark({
  className,
  tone = INK,
  splitAt,
  splitTone = CREAM,
  style,
}: MarkProps & { splitAt?: number; splitTone?: string }) {
  // scoped per instance, so two glasses on one page never share a gradient
  const gradientId = useId();
  if (splitAt === undefined) {
    return (
      <svg className={className} style={style} viewBox={GLASS_VIEWBOX} fill={tone} aria-hidden="true">
        <path d={GLASS_PATH} />
      </svg>
    );
  }
  const stop = `${(splitAt * 100).toFixed(2)}%`;
  return (
    <svg className={className} style={style} viewBox={GLASS_VIEWBOX} aria-hidden="true">
      <defs>
        {/* two stops at one offset = a hard edge, no blend */}
        <linearGradient id={gradientId} x1="0" y1="0" x2="1" y2="0">
          <stop offset={stop} stopColor={tone} />
          <stop offset={stop} stopColor={splitTone} />
        </linearGradient>
      </defs>
      <path d={GLASS_PATH} fill={`url(#${gradientId})`} />
    </svg>
  );
}

/**
 * Cacao pod.
 *
 * Leave `ribTone` off and the ribs stay open so whatever sits behind shows
 * through — that is how the reference draws it, over cream. Set it to put the pod
 * on green or wine without the ribs vanishing.
 */
export function CacaoPodMark({ className, tone = INK, ribTone, style }: MarkProps & { ribTone?: string }) {
  return (
    <svg className={className} style={style} viewBox={POD_VIEWBOX} aria-hidden="true">
      {ribTone === undefined ? (
        <path d={POD_OUTLINE + POD_RIBS} fill={tone} fillRule="evenodd" />
      ) : (
        <>
          <path d={POD_OUTLINE} fill={tone} />
          <path d={POD_RIBS} fill={ribTone} />
        </>
      )}
    </svg>
  );
}

/** The didone ampersand lifted out of the couple's lockup. */
export function Ampersand({ className, tone = INK, style }: MarkProps) {
  return (
    <svg className={className} style={style} viewBox={AMPERSAND_VIEWBOX} fill={tone} aria-hidden="true">
      <path d={AMPERSAND_PATH} fillRule="evenodd" />
    </svg>
  );
}

/** The dome the pod stands under. */
export function ArchMark({ className, tone = WINE, style }: MarkProps) {
  return (
    <svg className={className} style={style} viewBox="0 0 100 60" preserveAspectRatio="none" aria-hidden="true">
      <path d="M0 60V30A50 30 0 0 1 100 30V60Z" fill={tone} />
    </svg>
  );
}

/** The angled block that cuts across the lower half of the reference. */
export function WedgeMark({ className, tone = FOREST, flip = false, style }: MarkProps & { flip?: boolean }) {
  return (
    <svg className={className} style={style} viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
      <path d={flip ? 'M100 0V100H0Z' : 'M0 0H100V100Z'} fill={tone} />
    </svg>
  );
}

/** The speckled disc — the chocolate note in the composition. */
export function SpeckleDisc({ className, tone = INK, style }: MarkProps) {
  const id = useId();
  const grain = `${id}-grain`;
  const clip = `${id}-clip`;
  return (
    <svg className={className} style={style} viewBox="0 0 100 100" aria-hidden="true">
      <defs>
        <filter id={grain}>
          <feTurbulence type="fractalNoise" baseFrequency=".9" numOctaves="3" seed="7" />
          <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0" />
        </filter>
        <clipPath id={clip}>
          <circle cx="50" cy="50" r="50" />
        </clipPath>
      </defs>
      <circle cx="50" cy="50" r="50" fill={tone} />
      <g clipPath={`url(#${clip})`}>
        <rect width="100" height="100" filter={`url(#${grain})`} opacity=".55" />
      </g>
    </svg>
  );
}

/** The soft shoulder that turns a flat colour field into the reference's silhouette. */
export function ShoulderMark({ className, tone = CREAM, style }: MarkProps) {
  return (
    <svg className={className} style={style} viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
      <path d="M0 0H100V58A42 42 0 0 1 58 100H0Z" fill={tone} />
    </svg>
  );
}
